# Generated by Django 4.0.6 on 2022-09-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cash_flow_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cash_flow_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cash_flow_Sub_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=255)),
                ('ledger_opening_bal', models.IntegerField(blank=True, null=True)),
                ('ledger_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_inflow_outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger1')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cash_flow_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Group_inflow_outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cash_flow_groups')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.months')),
            ],
        ),
        migrations.AddField(
            model_name='cash_flow_sub',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_inflow_outflow'),
        ),
        migrations.AddField(
            model_name='cash_flow_sub',
            name='Sub_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cash_flow_sub_group'),
        ),
        migrations.CreateModel(
            name='cash_flow_Ledger_Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Vch_Type', models.CharField(max_length=255)),
                ('Vch_No', models.IntegerField()),
                ('Debit', models.IntegerField(blank=True, null=True)),
                ('Credit', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Ledger_inflow_outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger_inflow_outflow')),
                ('Particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inflow', models.IntegerField(blank=True, null=True)),
                ('Outflow', models.IntegerField(blank=True, null=True)),
                ('NetFlow', models.IntegerField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.months')),
            ],
        ),
    ]
