# Generated by Django 4.0.6 on 2022-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_inflow_outflow',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
