# Generated by Django 4.0.6 on 2022-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Opening_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
