# Generated by Django 4.0.6 on 2022-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cash_flow_sub_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_inflow_outflow',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
