# Generated by Django 4.0.6 on 2022-09-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_inflow_outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups')),
            ],
        ),
    ]
