# Generated by Django 4.0.6 on 2022-09-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ledger_inflow_outflow_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger1',
            new_name='Ledger',
        ),
    ]
