# Generated by Django 4.0.6 on 2022-09-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_group_inflow_outflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_inflow_outflow')),
                ('Sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_group')),
            ],
        ),
    ]
