# Generated by Django 4.0.6 on 2022-09-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sub_group_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups'),
        ),
    ]
