# Generated by Django 4.0.6 on 2022-09-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sub_type_alter_sub_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_inflow_outflow'),
        ),
    ]
