# Generated by Django 4.0.6 on 2022-09-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sub_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_inflow_outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub')),
            ],
        ),
    ]
