# Generated by Django 4.0.6 on 2022-09-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ledger_inflow_outflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Vch_Type', models.CharField(max_length=255)),
                ('Vch_No', models.IntegerField()),
                ('Debit', models.IntegerField(blank=True, null=True)),
                ('Credit', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Ledger_inflow_outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger_inflow_outflow')),
                ('Particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ledger')),
            ],
        ),
    ]
