# Generated by Django 4.0.6 on 2022-09-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_ledger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inflow', models.IntegerField(blank=True, null=True)),
                ('Outflow', models.IntegerField(blank=True, null=True)),
                ('NetFlow', models.IntegerField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.months')),
            ],
        ),
    ]
