# Generated by Django 4.0.6 on 2022-09-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_group_inflow_outflow_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cash_flow',
            new_name='Flow',
        ),
    ]
